baseURL = "http://python-shoman.me/"
languageCode = "en-us"
title = "Python Course"
theme = "book"
staticDir = ["static"]
enableEmoji = true


[markup]
[markup.goldmark.renderer]
  unsafe = true


[params]
    BookTheme = "light"
    BookLogo = "python-logo.png"
    BookMenuBundle = "/menu"

